<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\LISSTech.EntitySync.Core.csproj" />
    <ProjectReference Include="..\Ports\LISSTech.EntitySync.Ports.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="LISSTech.EntitySync" />
  </ItemGroup>
</Project>
